updating dotfiles from ip-192-168-86-217.ec2.internal

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -5,38 +5,46 @@
 #
 TMP=~/tmp
 REMOTE=false
+FRESH_INSTALL=$(command -v brew &> /dev/null && echo 0 || echo 1)
 
 function main {
   REMOTE_OMZ=https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
 
   # install homebrew
-  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  if ! command -v brew &> /dev/null; then
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 
-  # install curl, zsh
-  brew install curl
-  brew install zsh
+    # install curl, zsh
+    brew install curl
+  fi
 
-  # silently install oh-my-zsh
-  curl \
-    -fsSL $REMOTE_OMZ \
-    -o $TMP/omz.sh
-  sed -i '' '/exec zsh/d' $TMP/omz.sh
-  sh $TMP/omz.sh
-  rm -rf $TMP/omz.sh
-  ZSH_CUSTOM=~/.oh-my-zsh/custom
-  
-  # install powerlevel9k
-  git clone \
-    https://github.com/bhilburn/powerlevel9k.git \
-    $ZSH_CUSTOM/themes/powerlevel9k
-  
-  # install zsh-syntax-highlighting
-  git clone \
-    https://github.com/zsh-users/zsh-syntax-highlighting.git \
-    $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
 
-  # install vscode
-  brew cask install visual-studio-code
+  # if there is no .oh-my-zsh directory
+  if [[ !(-d ~/.oh-my-zsh) ]]; then
+    # silently install oh-my-zsh
+    curl \
+      -fsSL $REMOTE_OMZ \
+      -o $TMP/omz.sh
+    sed -i '' '/exec zsh/d' $TMP/omz.sh
+    sh $TMP/omz.sh
+    rm -rf $TMP/omz.sh
+    ZSH_CUSTOM=~/.oh-my-zsh/custom
+
+    # install powerlevel10k
+      git clone --depth=1 \
+        https://github.com/romkatv/powerlevel10k.git \
+        $ZSH_CUSTOM/themes/powerlevel10k
+
+    # install zsh-syntax-highlighting
+    git clone \
+      https://github.com/zsh-users/zsh-syntax-highlighting.git \
+      $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
+  fi
+
+  if ! command -v code &> /dev/null; then
+    # install vscode
+    brew cask install visual-studio-code
+  fi
 
   # install slack
   brew cask install slack
@@ -57,20 +65,6 @@ mkdir $TMP
 if [[ !(-d ~/.oh-my-zsh) ]]; then
   main
 fi
-
-# check for remote install
-# if remote, change .zshrc to reflect correct changes.
-# if [[ !(-z ${SSH_CONNECTION+x}) ]]; then
-#     REMOTE=true
-#     touch $TMP/.zshrc.remote
-#     mv $DOTFILES/.zshrc $TMP
-#     cat $TMP/.zshrc |
-#     sed -e 's/code/vim/g' |
-#     sed '/WORKON/d' |
-#     sed '/virtualenvwrapper/d' |
-#     sed '141,$ d' >> $TMP/.zshrc.remote
-#     mv $TMP/.zshrc.remote $DOTFILES/.zshrc
-# fi
      
 # copy necessary files to ~
 cp ./src/.zshrc ~
